import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
  root: { flex: 1, minHeight: 0, minWidth: 0, marginBottom: 94, backgroundColor: '#72cbd0', overflow: 'hidden' },
  sceneImage: { width: '100%', height: '100%' },
  canvas: { position: 'absolute', overflow: 'hidden' },
  fill: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0 },
  controls: { position: 'absolute', top: 8, bottom: 8, right: 8, width: '23%', backgroundColor: '#fffaf0', borderRadius: 18, padding: 10, alignItems: 'center', justifyContent: 'space-evenly', gap: 4 },
  back: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, minHeight: 44, alignSelf: 'stretch' },
  backText: { color: '#237d75', fontWeight: '800', fontSize: 16 },
  progressGroup: { alignSelf: 'stretch', gap: 8 },
  instruction: { color: '#386664', fontWeight: '800', fontSize: 15, textAlign: 'center' },
  track: { height: 12, backgroundColor: '#dbe9de', borderRadius: 8, overflow: 'hidden' },
  progress: { height: '100%', borderRadius: 8, backgroundColor: '#42b99b' },
  action: { minHeight: 48, alignSelf: 'stretch', alignItems: 'center', justifyContent: 'center', backgroundColor: '#ffdc79', borderRadius: 14, padding: 8, flexDirection: 'row', gap: 6 },
  actionText: { fontSize: 16, fontWeight: '900', color: '#644222', flexShrink: 1, textAlign: 'center' },
  success: { color: '#237d75', fontWeight: '900', fontSize: 18, textAlign: 'center' },
  toolImage: { width: 48, height: 48 },
  cursorImage: { width: '100%', height: '100%' },
  disabled: { opacity: 0.45 },
  zoneAsset: { position: 'absolute' },
  zoneImage: { width: '100%', height: '100%' },
  wetDropCenter: { position: 'absolute', left: '30%', top: '6%', width: '40%', height: '65%' },
  wetDropLeft: { position: 'absolute', left: '3%', top: '39%', width: '27%', height: '44%' },
  wetDropRight: { position: 'absolute', right: 0, top: '48%', width: '30%', height: '50%' },
  waterParticle: { position: 'absolute' },
  cursor: { position: 'absolute', zIndex: 8 },
  handShowerWater: { position: 'absolute', left: '11%', top: '35%', width: '38%', height: '56%' },
  privacy: { position: 'absolute', left: '12%', right: '35%', top: '43%', bottom: '13%', backgroundColor: '#83cbbf', borderColor: '#ffe9ad', borderWidth: 4, borderRadius: 16, flexDirection: 'row', justifyContent: 'space-evenly', alignItems: 'center' },
  curtainFold: { height: '100%', width: '3%', backgroundColor: '#60b1a9' },
  sparkle: { position: 'absolute', color: '#fff7a4', fontSize: 32, fontWeight: '900' },
});
