import { StyleSheet } from 'react-native';
export const feedingHeartPositions = [
  { x: .28, y: .40, size: .85, drift: -.025 },
  { x: .63, y: .40, size: 1, drift: .03 },
  { x: .29, y: .27, size: .7, drift: -.04 },
  { x: .62, y: .25, size: .8, drift: .04 },
  { x: .35, y: .20, size: .6, drift: -.025 },
  { x: .54, y: .20, size: .65, drift: .025 },
];
export const styles = StyleSheet.create({
  room: { flex: 1, minHeight: 0, marginBottom: 94, backgroundColor: '#eedcaf', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  scene: { position: 'relative', overflow: 'hidden' },
  image: { width: '100%', height: '100%' },
  fill: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 },
  roomImage: { position: 'absolute' },
  cat: { position: 'absolute', width: 230, height: 284, zIndex: 2 },
  exit: { position: 'absolute', zIndex: 5 },
  root: { userSelect: 'none', flex: 1, minHeight: 0, marginBottom: 94, backgroundColor: '#ecdcb9', overflow: 'hidden' },
  canvas: { position: 'absolute', overflow: 'hidden', borderRadius: 16 },
  panel: { position: 'absolute', top: 6, bottom: 6, right: 8, width: '25%', backgroundColor: '#fff9e9', borderRadius: 18 },
  panelContent: { flexGrow: 1, padding: 10, gap: 8, justifyContent: 'space-evenly', alignItems: 'stretch' },
  title: { color: '#277d75', fontSize: 19, fontWeight: '900', textAlign: 'center' },
  text: { color: '#655038', fontSize: 14, textAlign: 'center', fontWeight: '600' },
  message: { color: '#956019', fontSize: 13, textAlign: 'center', fontWeight: '700' },
  action: { minHeight: 44, borderRadius: 14, padding: 8, backgroundColor: '#ffdb7b', justifyContent: 'center', alignItems: 'center' },
  secondary: { backgroundColor: '#d9eee4' },
  actionText: { color: '#335e54', fontWeight: '900', fontSize: 15, textAlign: 'center' },
  disabled: { opacity: .4 },
  track: { height: 10, backgroundColor: '#dbe9de', borderRadius: 8, overflow: 'hidden' },
  progress: { height: '100%', backgroundColor: '#43b89a', borderRadius: 8 },
  foodSlot: { position: 'absolute', width: '32%', height: '24%', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', overflow: 'hidden', borderRadius: 14, borderWidth: 2, borderColor: 'transparent' },
  foodSelected: { backgroundColor: '#fff2b975', borderColor: '#f4c34e' },
  foodImage: { width: '40%', height: '90%' },
  foodLabel: { flexShrink: 1, maxWidth: '60%', backgroundColor: '#fffaf1f5', paddingHorizontal: 3, paddingVertical: 3, borderRadius: 8 },
  foodLabelText: { color: '#32685e', fontSize: 10, fontWeight: '900', textAlign: 'center' },
  selection: { flexDirection: 'row', justifyContent: 'center', gap: 4 },
  selectedIcon: { width: 36, height: 36 },
  vessel: { position: 'absolute', left: '19%', top: '33%', width: '51%', height: '51%' },
  potFood: { position: 'absolute', left: '29%', top: '37%', width: '31%', height: '25%', borderRadius: 999, overflow: 'hidden' },
  bowl: { position: 'absolute', left: '28%', top: '73%', width: '33%', height: '25%' },
  bowlFood: { position: 'absolute', left: '34%', top: '75%', width: '21%', height: '11%', borderRadius: 999, overflow: 'hidden' },
  ingredient: { position: 'absolute', width: '43%', height: '83%', top: '8%' },
  spoon: { position: 'absolute', width: '25%', height: '25%', zIndex: 9 },
  spoonFood: { position: 'absolute', left: '4%', top: '2%', width: '40%', height: '45%' },
  heat: { position: 'absolute', left: '27%', top: '59%', width: '36%', height: '16%', borderRadius: 999, backgroundColor: '#ff934f', borderWidth: 4, borderColor: '#ffe093' },
  steam: { position: 'absolute', left: '34%', top: '25%', color: '#fffdf0', fontSize: 48, fontWeight: '900' },
  heart: { position: 'absolute' },
  assetButton: { minHeight: 188, flexShrink: 0, alignSelf: 'center', alignItems: 'center', justifyContent: 'center', padding: 12 },
  assetButtonArt: { width: 164, height: 164 },
  assetCaption: { fontSize: 12, color: '#33786d', fontWeight: '800', textAlign: 'center' },
  dragTray: { flexDirection: 'row', gap: 5, minHeight: 82 },
  dragCard: { userSelect: 'none', flex: 1, minWidth: 0, height: 82, borderRadius: 12, backgroundColor: '#e3f0df', borderWidth: 2, borderColor: '#eed39c' },
  dragCardContent: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 3 },
  dragCardImage: { width: '100%', height: 56 },
  dragOverlay: { position: 'absolute', zIndex: 30 },
  blowingCat: { position: 'absolute', left: '58%', top: '21%', width: '40%', height: '63%' },
  playAction: { flexDirection: 'row', gap: 8 },
});
