import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  brushHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 18,
  },
  canvas: {
    backgroundColor: '#ffffff',
    borderColor: '#f0dcc0',
    borderRadius: 8,
    borderWidth: 3,
    aspectRatio: 1,
    overflow: 'hidden',
    width: '100%',
  },
  colorButton: {
    borderColor: '#ffffff',
    borderRadius: 999,
    borderWidth: 3,
    height: 34,
    width: 34,
  },
  content: {
    flex: 1,
    minHeight: 0,
    overflow: 'hidden',
    padding: 14,
    paddingBottom: 132,
  },
  controlLabel: {
    color: '#372413',
    fontSize: 16,
    fontWeight: '900',
  },
  controls: {
    backgroundColor: '#fffaf0',
    borderColor: '#f0dcc0',
    borderRadius: 8,
    borderWidth: 2,
    marginTop: 14,
    padding: 14,
  },
  eraserButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderColor: '#57b8a9',
    borderRadius: 8,
    borderWidth: 2,
    flexDirection: 'row',
    gap: 8,
    marginTop: 16,
    minHeight: 44,
    paddingHorizontal: 14,
  },
  activeEraserButton: {
    backgroundColor: '#dff4ff',
  },
  eraserButtonText: {
    color: '#26796e',
    fontSize: 15,
    fontWeight: '900',
  },
  header: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderBottomColor: '#f0dcc0',
    borderBottomWidth: 2,
    flexDirection: 'row',
    gap: 14,
    paddingBottom: 8,
    paddingHorizontal: 12,
    paddingTop: 8,
  },
  palette: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 10,
  },
  screen: {
    backgroundColor: '#fff7e8',
    flex: 1,
    overflow: 'hidden',
  },
  selectedColor: {
    borderColor: '#372413',
    transform: [{ scale: 1.15 }],
  },
  slider: {
    height: 34,
    justifyContent: 'center',
    marginTop: 6,
  },
  sliderThumb: {
    backgroundColor: '#ff7a59',
    borderColor: '#ffffff',
    borderRadius: 999,
    borderWidth: 3,
    height: 26,
    marginLeft: -13,
    position: 'absolute',
    width: 26,
  },
  sliderTrack: {
    backgroundColor: '#f1c232',
    borderRadius: 999,
    height: 8,
    width: '100%',
  },
  title: {
    color: '#372413',
    flex: 1,
    fontSize: 24,
    fontWeight: '900',
    textAlign: 'left',
  },
  titleGroup: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 2,
    marginLeft: 8,
  },
});
