import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  card: {
    backgroundColor: '#ffffff',
    borderColor: '#f0dcc0',
    borderRadius: 8,
    borderWidth: 2,
    flex: 1,
    margin: 10,
    minHeight: 0,
    padding: 14,
  },
  celebrationOverlay: {
    alignItems: 'center',
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  audioPromptDrawing: {
    alignSelf: 'center',
    flex: 1,
    maxWidth: 180,
    minHeight: 0,
    width: '18%',
  },
  feedback: {
    color: '#ff7a59',
    fontSize: 24,
    fontWeight: '900',
    marginBottom: 6,
    minHeight: 26,
    textAlign: 'center',
  },
  disabledOption: {
    opacity: 0.35,
  },
  levelInfo: {
    flex: 1,
    paddingHorizontal: 10,
  },
  levelHeaderTitle: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 2,
  },
  levelTitle: {
    color: '#372413',
    fontSize: 18,
    fontWeight: '900',
  },
  matchBoard: {
    alignSelf: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 18,
    maxWidth: 780,
    minHeight: 0,
    width: '52%',
  },
  matchColumn: {
    alignItems: 'center',
    flex: 1,
    gap: 8,
    minHeight: 0,
  },
  matchPicture: {
    alignItems: 'center',
    backgroundColor: '#fff7e8',
    borderColor: '#f0dcc0',
    borderRadius: 8,
    borderWidth: 2,
    aspectRatio: 1,
    flexGrow: 0,
    height: '22%',
    justifyContent: 'center',
    padding: 6,
  },
  matchPictureMain: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    width: '100%',
  },
  matchPictureDrawing: {
    alignSelf: 'center',
    maxHeight: 92,
    width: '78%',
  },
  matchAudioButton: {
    marginBottom: 4,
  },
  matchWord: {
    alignItems: 'center',
    backgroundColor: '#dff4ff',
    borderColor: '#9ed3ea',
    borderRadius: 8,
    borderWidth: 2,
    aspectRatio: 1,
    flexGrow: 0,
    height: '22%',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  matchWordMain: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    width: '100%',
  },
  matchWordText: {
    color: '#22313b',
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  matched: {
    opacity: 0.35,
  },
  option: {
    alignItems: 'center',
    backgroundColor: '#fff7e8',
    borderColor: '#f0dcc0',
    borderRadius: 8,
    borderWidth: 2,
    flexBasis: '23%',
    flexGrow: 1,
    justifyContent: 'center',
    minHeight: 0,
    padding: 8,
  },
  optionMain: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    width: '100%',
  },
  optionText: {
    color: '#372413',
    fontSize: 18,
    fontWeight: '900',
    marginTop: 8,
    textAlign: 'center',
  },
  optionsGrid: {
    alignItems: 'stretch',
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    minHeight: 0,
  },
  pictureCaption: {
    color: '#6c5a42',
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 16,
    marginTop: 2,
    textAlign: 'center',
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#ff7a59',
    borderRadius: 8,
    justifyContent: 'center',
    marginTop: 28,
    minHeight: 58,
    paddingHorizontal: 16,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '900',
  },
  progressText: {
    color: '#76624a',
    fontSize: 14,
    fontWeight: '800',
    marginTop: 2,
  },
  prompt: {
    color: '#22313b',
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 28,
    textAlign: 'center',
  },
  promptRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    marginBottom: 8,
    minHeight: 48,
  },
  resultCard: {
    alignItems: 'center',
    backgroundColor: '#f6c445',
    borderColor: '#e1a827',
    borderRadius: 20,
    borderWidth: 2,
    maxWidth: 390,
    padding: 5,
    width: '100%',
  },
  resultCardInner: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#57b8a9',
    borderRadius: 14,
    borderWidth: 3,
    padding: 22,
    width: '100%',
  },
  resultArea: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  resultDecorations: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 30,
    marginBottom: 8,
  },
  resultCoins: {
    color: '#b77900',
    fontSize: 24,
    fontWeight: '900',
    textAlign: 'center',
  },
  resultCoinsRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 14,
  },
  resultCoinImage: {
    height: 34,
    width: 34,
  },
  resultKicker: {
    color: '#57b8a9',
    fontSize: 18,
    fontWeight: '900',
  },
  resultTitle: {
    color: '#372413',
    fontSize: 32,
    fontWeight: '900',
    marginTop: 8,
    textAlign: 'center',
  },
  screen: {
    backgroundColor: '#fff7e8',
    flex: 1,
    paddingTop: 0,
  },
  selectedMatch: {
    backgroundColor: '#ffe1d6',
    borderColor: '#ff7a59',
  },
  translationOption: {
    minHeight: 0,
  },
  audioOption: {
    backgroundColor: '#e9f8ff',
  },
  topBar: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 14,
  },
});
