import { StyleSheet } from 'react-native';

export const WIDE_ROOM_WIDTH = 1300;
export const KITCHEN_ROOM_WIDTH = 760;
export const BATHROOM_ROOM_WIDTH = 720;
export const EXTERIOR_YARD_WIDTH = 960;
export const ROOM_HEIGHT = 450;
export const ROOM_FLOOR_HEIGHT = 184;

export const styles = StyleSheet.create({
  bathroomDoorHit: {
    height: 148,
    position: 'absolute',
    right: 54,
    top: 82,
    width: 108,
    zIndex: 1,
  },
  bathroomCat: {
    position: 'absolute',
    zIndex: 4,
  },
  bathroomTouch: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 0,
  },
  clickSparkle: {
    zIndex: 20,
  },
  bathroomExitDoorHit: {
    height: 204,
    left: 36,
    position: 'absolute',
    top: 50,
    width: 132,
    zIndex: 8,
  },
  bathroomPane: {
    backgroundColor: '#ffffff',
    height: ROOM_HEIGHT - 4,
    overflow: 'hidden',
    position: 'relative',
    width: BATHROOM_ROOM_WIDTH,
  },
  doorTileButton: {
    bottom: 6,
    height: 112,
    left: 92,
    position: 'absolute',
    width: 110,
    zIndex: 3,
  },
  emptyInventory: {
    backgroundColor: '#ffffff',
    borderColor: '#f0dcc0',
    borderRadius: 8,
    borderWidth: 2,
    padding: 16,
    width: '100%',
  },
  fixedFurniture: {
    left: 0,
    position: 'absolute',
    top: 0,
    zIndex: 3,
  },
  furnitureImage: {
    height: '100%',
    width: '100%',
  },
  drawingArtwork: {
    aspectRatio: 1,
    left: 15,
    overflow: 'hidden',
    position: 'absolute',
    top: 15,
    width: 150,
    zIndex: 1,
  },
  drawingFrameHit: {
    aspectRatio: 1,
    left: 468,
    overflow: 'hidden',
    position: 'absolute',
    top: 76,
    width: 180,
    zIndex: 8,
  },
  emptyText: {
    color: '#6c5a42',
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 22,
    textAlign: 'center',
  },
  exteriorCat: {
    position: 'absolute',
    zIndex: 4,
  },
  exteriorBarn: {
    height: 174,
    left: 706,
    position: 'absolute',
    top: 50,
    width: 190,
    zIndex: 1,
  },
  exteriorBarnImage: {
    height: '100%',
    width: '100%',
  },
  exteriorTouch: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 0,
  },
  frontYardAnimal: {
    zIndex: 4,
  },
  exteriorHouseBody: {
    alignItems: 'center',
    bottom: 145,
    height: 214,
    left: EXTERIOR_YARD_WIDTH / 2 - 146,
    position: 'absolute',
    transform: [{ scale: 1.2 }],
    width: 293,
    zIndex: 3,
  },
  exteriorWide: {
    height: ROOM_HEIGHT - 4,
    position: 'relative',
    width: EXTERIOR_YARD_WIDTH,
  },
  floor: {
    bottom: 0,
    left: 0,
    height: ROOM_FLOOR_HEIGHT,
    position: 'absolute',
    right: 0,
    width: '100%',
    zIndex: 4,
  },
  floorTouch: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 0,
  },
  furnitureStage: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 6,
  },
  header: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderBottomColor: '#f0dcc0',
    borderBottomWidth: 2,
    paddingBottom: 6,
    paddingHorizontal: 14,
    paddingTop: 6,
  },
  headerTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  insideDoorHit: {
    height: 178,
    left: 682,
    position: 'absolute',
    top: 68,
    width: 166,
    zIndex: 1,
  },
  inventoryScroll: {
    paddingBottom: 128,
  },
  inventorySection: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 8,
  },
  mainRoomPane: {
    backgroundColor: '#ffffff',
    height: ROOM_HEIGHT - 4,
    overflow: 'hidden',
    position: 'relative',
    width: WIDE_ROOM_WIDTH,
  },
  kitchenCat: {
    position: 'absolute',
    zIndex: 4,
  },
  kitchenDoorHit: {
    height: 190,
    left: 278,
    position: 'absolute',
    top: 68,
    width: 154,
    zIndex: 1,
  },
  kitchenExitDoorHit: {
    height: 204,
    position: 'absolute',
    right: 22,
    top: 62,
    width: 132,
    zIndex: 8,
  },
  kitchenPane: {
    backgroundColor: '#ffffff',
    height: ROOM_HEIGHT - 4,
    overflow: 'hidden',
    position: 'relative',
    width: KITCHEN_ROOM_WIDTH,
  },
  kitchenTouch: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 0,
  },
  houseImage: {
    height: '100%',
    width: '100%',
  },
  inventoryCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#f0dcc0',
    borderRadius: 8,
    borderWidth: 2,
    flexBasis: '30.6%',
    height: 104,
    justifyContent: 'center',
    padding: 8,
  },
  inventoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  inventoryName: {
    color: '#372413',
    fontSize: 12,
    fontWeight: '900',
    marginTop: 5,
    textAlign: 'center',
  },
  inventoryImage: {
    height: 46,
    width: '100%',
  },
  inventoryAnimalImage: {
    height: 64,
    width: '100%',
  },
  inventoryPreview: {
    alignItems: 'center',
    borderRadius: 8,
    height: 48,
    justifyContent: 'center',
    width: '100%',
  },
  placedInventoryCard: {
    borderColor: '#57b8a9',
    borderWidth: 5,
  },
  room: {
    backgroundColor: '#ffffff',
    borderColor: '#f0dcc0',
    borderRadius: 8,
    borderWidth: 2,
    borderLeftWidth: 0,
    borderRightWidth: 0,
    height: ROOM_HEIGHT,
    overflow: 'hidden',
  },
  roomCat: {
    position: 'absolute',
    zIndex: 20,
  },
  roomBackgroundImage: {
    borderRadius: 6,
  },
  sceneArea: {
    paddingBottom: 0,
    paddingHorizontal: 0,
    paddingTop: 0,
  },
  screen: {
    backgroundColor: '#fff7e8',
    flex: 1,
  },
  title: {
    color: '#372413',
    flex: 1,
    fontSize: 24,
    fontWeight: '900',
    textAlign: 'left',
  },
  titleGroup: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 2,
    marginLeft: 8,
  },
  yardAnimal: {
    alignItems: 'center',
    height: 104,
    justifyContent: 'center',
    position: 'absolute',
    width: 104,
    zIndex: 2,
  },
  yardAnimalImage: {
    height: 100,
    width: 100,
  },
  cowYardAnimalImage: {
    height: 110,
    width: 110,
  },
  horseYardAnimalImage: {
    height: 112,
    width: 112,
  },
});
