import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  completedPoint: { backgroundColor: '#57b8a9', borderColor: '#d7f5cf' },
  disabledPlayButton: { backgroundColor: '#c8bba8' },
  levelNumber: { color: '#ffffff', fontWeight: '900', marginTop: 1 },
  levelPoint: { alignItems: 'center', backgroundColor: '#ff7a59', borderColor: '#fff3b0', borderWidth: 5, justifyContent: 'center', shadowColor: '#754012', shadowOffset: { height: 3, width: 0 }, shadowOpacity: 0.28, shadowRadius: 3 },
  levelPointWrap: { alignItems: 'center', justifyContent: 'center', position: 'absolute', zIndex: 5 },
  lockedPoint: { backgroundColor: '#d8cec0', borderColor: '#eee7dc' },
  lockedText: { color: '#7f7569' },
  mapImage: { borderRadius: 6 },
  mapScene: { flex: 1, overflow: 'hidden', position: 'relative' },
  lockedNextWorldButton: { opacity: 0.42 },
  modalBackdrop: { alignItems: 'center', backgroundColor: 'rgba(31, 40, 45, 0.48)', flex: 1, justifyContent: 'center', padding: 22 },
  modalCard: { alignItems: 'center', backgroundColor: '#ffffff', borderColor: '#fff3b0', borderRadius: 8, borderWidth: 3, maxWidth: 420, padding: 22, width: '100%' },
  modalDescription: { color: '#5f5344', fontSize: 17, fontWeight: '700', lineHeight: 24, marginTop: 12, textAlign: 'center' },
  modalIconWrap: { alignItems: 'center', backgroundColor: '#ff7a59', borderRadius: 40, height: 80, justifyContent: 'center', marginBottom: 12, width: 80 },
  modalKicker: { color: '#57b8a9', fontSize: 16, fontWeight: '900' },
  modalTheme: { color: '#76624a', fontSize: 16, fontWeight: '900', marginTop: 4 },
  modalTitle: { color: '#372413', fontSize: 28, fontWeight: '900', marginTop: 4, textAlign: 'center' },
  nextWorldButton: { alignItems: 'center', justifyContent: 'center', position: 'absolute', zIndex: 6 },
  nextWorldImage: { height: '100%', width: '100%' },
  playButton: { alignItems: 'center', backgroundColor: '#ff7a59', borderRadius: 8, justifyContent: 'center', marginTop: 18, minHeight: 58, width: '100%' },
  playButtonText: { color: '#ffffff', fontSize: 20, fontWeight: '900' },
  rewardRow: { alignItems: 'center', backgroundColor: '#fff3b0', borderRadius: 8, flexDirection: 'row', gap: 8, marginTop: 16, paddingHorizontal: 12, paddingVertical: 10 },
  rewardText: { color: '#744d00', fontSize: 16, fontWeight: '900' },
  screen: { backgroundColor: '#fff7e8', flex: 1 },
});
