import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  bushImage: {
    height: 46,
    position: 'absolute',
    width: 76,
    zIndex: 3,
  },
  bushOne: {
    left: 18,
    top: 420,
  },
  bushFive: {
    right: 18,
    top: 1168,
  },
  bushFour: {
    left: 24,
    top: 900,
  },
  bushThree: {
    right: 24,
    top: 610,
  },
  bushTwo: {
    right: 18,
    top: 278,
  },
  cloud: {
    backgroundColor: '#ffffff',
    borderRadius: 999,
    height: 34,
    opacity: 0.9,
    position: 'absolute',
    width: 92,
  },
  cloudOne: {
    left: 30,
    top: 74,
  },
  cloudTwo: {
    right: 28,
    top: 130,
  },
  completedPoint: {
    backgroundColor: '#57b8a9',
    borderColor: '#d7f5cf',
  },
  content: {
    paddingBottom: 112,
  },
  disabledPlayButton: {
    backgroundColor: '#c8bba8',
  },
  header: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderBottomColor: '#f0dcc0',
    borderBottomWidth: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 8,
    paddingHorizontal: 20,
    paddingTop: 8,
  },
  ground: {
    backgroundColor: '#78c85f',
    borderTopColor: '#5faf4f',
    borderTopWidth: 4,
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 206,
  },
  landscape: {
    backgroundColor: '#9edaf7',
    borderColor: '#77c1e4',
    borderRadius: 0,
    borderWidth: 2,
    height: 1536,
    overflow: 'hidden',
    position: 'relative',
  },
  landscapeImage: {
    borderRadius: 0,
    height: '100%',
    width: '100%',
  },
  landscapeViewport: {
    height: 1536,
    overflow: 'hidden',
    width: '100%',
  },
  levelCaption: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 8,
    color: '#372413',
    fontSize: 14,
    fontWeight: '900',
    marginTop: 7,
    maxWidth: 118,
    paddingHorizontal: 8,
    paddingVertical: 5,
    textAlign: 'center',
  },
  levelNumber: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '900',
    marginTop: 2,
  },
  levelPoint: {
    alignItems: 'center',
    backgroundColor: '#ff7a59',
    borderColor: '#fff3b0',
    borderRadius: 44,
    borderWidth: 5,
    height: 88,
    justifyContent: 'center',
    width: 88,
  },
  levelPointWrap: {
    alignItems: 'center',
    marginLeft: -44,
    position: 'absolute',
    zIndex: 5,
  },
  lockedPoint: {
    backgroundColor: '#d8cec0',
    borderColor: '#eee7dc',
  },
  lockedText: {
    color: '#7f7569',
  },
  modalBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(31, 40, 45, 0.48)',
    flex: 1,
    justifyContent: 'center',
    padding: 22,
  },
  modalCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#fff3b0',
    borderRadius: 8,
    borderWidth: 3,
    maxWidth: 420,
    padding: 22,
    width: '100%',
  },
  modalDescription: {
    color: '#5f5344',
    fontSize: 17,
    fontWeight: '700',
    lineHeight: 24,
    marginTop: 12,
    textAlign: 'center',
  },
  modalIconWrap: {
    alignItems: 'center',
    backgroundColor: '#ff7a59',
    borderRadius: 40,
    height: 80,
    justifyContent: 'center',
    marginBottom: 12,
    width: 80,
  },
  modalKicker: {
    color: '#57b8a9',
    fontSize: 16,
    fontWeight: '900',
  },
  modalTheme: {
    color: '#76624a',
    fontSize: 16,
    fontWeight: '900',
    marginTop: 4,
  },
  modalTitle: {
    color: '#372413',
    fontSize: 28,
    fontWeight: '900',
    marginTop: 4,
    textAlign: 'center',
  },
  playButton: {
    alignItems: 'center',
    backgroundColor: '#ff7a59',
    borderRadius: 8,
    justifyContent: 'center',
    marginTop: 18,
    minHeight: 58,
    width: '100%',
  },
  playButtonText: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '900',
  },
  rewardRow: {
    alignItems: 'center',
    backgroundColor: '#fff3b0',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    marginTop: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  rewardText: {
    color: '#744d00',
    fontSize: 16,
    fontWeight: '900',
  },
  mountain: {
    borderBottomColor: '#6f9f7a',
    borderBottomWidth: 150,
    borderLeftColor: 'transparent',
    borderLeftWidth: 92,
    borderRightColor: 'transparent',
    borderRightWidth: 92,
    height: 0,
    position: 'absolute',
    top: 74,
    width: 0,
  },
  mountainCenter: {
    borderBottomColor: '#5e8e72',
    left: '24%',
    top: 52,
  },
  mountainLeft: {
    left: '-13%',
  },
  mountainRight: {
    right: '-12%',
  },
  mountains: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  puddle: {
    backgroundColor: '#69c7ef',
    borderColor: '#399ac2',
    borderRadius: 999,
    borderWidth: 2,
    height: 24,
    opacity: 0.9,
    position: 'absolute',
    transform: [{ rotate: '-7deg' }],
    width: 72,
  },
  puddleOne: {
    left: 28,
    top: 544,
  },
  puddleTwo: {
    right: 28,
    top: 374,
    transform: [{ rotate: '10deg' }],
  },
  puddleThree: {
    left: 34,
    top: 1052,
    transform: [{ rotate: '12deg' }],
  },
  roadSvg: {
    bottom: 0,
    left: 0,
    pointerEvents: 'none',
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 2,
  },
  screen: {
    backgroundColor: '#fff7e8',
    flex: 1,
  },
  sun: {
    backgroundColor: '#ffd966',
    borderColor: '#fff3b0',
    borderRadius: 44,
    borderWidth: 6,
    height: 88,
    position: 'absolute',
    right: 22,
    top: 24,
    width: 88,
  },
  title: {
    color: '#372413',
    fontSize: 24,
    fontWeight: '900',
  },
  titleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
  },
  tree: {
    alignItems: 'center',
    position: 'absolute',
    zIndex: 3,
  },
  treeOne: {
    left: 24,
    top: 252,
  },
  treeThree: {
    left: 32,
    top: 648,
  },
  treeFour: {
    right: 22,
    top: 778,
  },
  treeFive: {
    left: 26,
    top: 1120,
  },
  treeImage: {
    height: 92,
    width: 82,
  },
  treeTwo: {
    right: 26,
    top: 486,
  },
});
