import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  emptyBox: {
    backgroundColor: '#ffffff',
    borderColor: '#f0dcc0',
    borderRadius: 8,
    borderWidth: 2,
    padding: 18,
    width: '100%',
  },
  emptyText: {
    color: '#6c5a42',
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 22,
    textAlign: 'center',
  },
  equippedCard: {
    borderColor: '#ff7a59',
  },
  header: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderBottomColor: '#f0dcc0',
    borderBottomWidth: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 8,
    paddingHorizontal: 14,
    paddingTop: 8,
  },
  itemCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#f0dcc0',
    borderRadius: 8,
    borderWidth: 2,
    flexBasis: '31%',
    height: 104,
    justifyContent: 'center',
    padding: 12,
  },
  itemName: {
    color: '#372413',
    fontSize: 13,
    fontWeight: '900',
    marginTop: 6,
    textAlign: 'center',
  },
  itemPreview: {
    alignItems: 'center',
    borderRadius: 8,
    height: 52,
    justifyContent: 'center',
    paddingHorizontal: 8,
    width: '100%',
  },
  itemPreviewImage: {
    height: 54,
    width: '100%',
  },
  itemsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  itemsScroll: {
    paddingBottom: 128,
  },
  itemsSection: {
    flex: 1,
    paddingHorizontal: 20,
  },
  screen: {
    backgroundColor: '#fff7e8',
    flex: 1,
  },
  sectionTitle: {
    color: '#372413',
    fontSize: 24,
    fontWeight: '900',
    marginBottom: 8,
  },
  stage: {
    alignItems: 'center',
    borderColor: '#9ed3ea',
    borderRadius: 0,
    borderWidth: 2,
    height: 340,
    margin: 0,
    marginBottom: 12,
    overflow: 'hidden',
    width: '100%',
  },
  stageBackground: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'flex-end',
    width: '100%',
  },
  stageBackgroundImage: {
    height: '100%',
    borderRadius: 6,
    width: '100%',
  },
  title: {
    color: '#372413',
    flex: 1,
    fontSize: 24,
    fontWeight: '900',
    textAlign: 'left',
  },
  titleGroup: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 2,
    marginLeft: 8,
  },
});
