import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  buyButton: {
    alignItems: 'center',
    backgroundColor: '#ff7a59',
    borderRadius: 8,
    justifyContent: 'center',
    marginBottom: 2,
    marginTop: 4,
    minHeight: 32,
    width: '88%',
  },
  buyButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '900',
  },
  card: {
    alignItems: 'center',
    aspectRatio: 1,
    backgroundColor: '#ffffff',
    borderColor: '#f0dcc0',
    borderRadius: 8,
    borderWidth: 2,
    flexBasis: '23%',
    paddingBottom: 6,
    paddingHorizontal: 5,
    paddingTop: 5,
  },
  categoryIcon: {
    alignItems: 'center',
    borderRadius: 8,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  categoryCopy: {
    flex: 1,
    minWidth: 0,
  },
  content: {
    paddingHorizontal: 24,
    paddingTop: 10,
    paddingBottom: 128,
  },
  header: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#f0dcc0',
    borderBottomWidth: 2,
    flexDirection: 'row',
    gap: 14,
    minHeight: 66,
    paddingBottom: 5,
    paddingHorizontal: 18,
    paddingTop: 5,
  },
  headerInfo: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    minWidth: 0,
  },
  categoryTitle: {
    color: '#372413',
    fontSize: 19,
    fontWeight: '900',
    lineHeight: 23,
  },
  disabledButton: {
    backgroundColor: '#c8bba8',
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  itemName: {
    color: '#372413',
    fontSize: 14,
    fontWeight: '900',
    lineHeight: 17,
    marginTop: 1,
    textAlign: 'center',
  },
  message: {
    backgroundColor: '#d7f5cf',
    borderColor: '#5aa96a',
    borderRadius: 8,
    borderWidth: 2,
    color: '#2f6f3b',
    fontSize: 16,
    fontWeight: '900',
    marginBottom: 14,
    padding: 12,
    textAlign: 'center',
  },
  ownedBadge: {
    alignItems: 'center',
    backgroundColor: '#e4f6ef',
    borderColor: '#57b8a9',
    borderRadius: 8,
    borderWidth: 2,
    justifyContent: 'center',
    marginBottom: 2,
    marginTop: 4,
    minHeight: 32,
    width: '88%',
  },
  ownedBadgeText: {
    color: '#287568',
    fontSize: 14,
    fontWeight: '900',
  },
  ownedCard: {
    borderColor: '#57b8a9',
  },
  preview: {
    alignItems: 'center',
    borderRadius: 8,
    height: 68,
    justifyContent: 'center',
    paddingHorizontal: 8,
    width: '100%',
  },
  previewImage: {
    height: 60,
    width: '100%',
  },
  price: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
    justifyContent: 'center',
    marginTop: 0,
    minHeight: 22,
  },
  priceCoin: {
    height: 26,
    width: 26,
  },
  priceText: {
    color: '#76624a',
    fontSize: 16,
    fontWeight: '800',
  },
  screen: {
    backgroundColor: '#fff7e8',
    flex: 1,
  },
});
